---
# Docker compose file for self hosted GitLab Runner

services:
    gitlab-runner:
        image: gitlab/gitlab-runner:latest
        container_name: gitlab-runner
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config:/etc/gitlab-runner
        restart: unless-stopped
