---
# Docker compose file for self hosted Grafana

volumes:
    grafana: {}

services:
    grafana:
        image: grafana/grafana-oss
        container_name: grafana
        environment:
            - GF_SERVER_ROOT_URL=https://grafana.beenhamow.co.uk
            - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
        volumes:
            - grafana:/var/lib/grafana
        ports:
            - 3000:3000
        restart: unless-stopped
