---
# Docker compose file for my homepage

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    env_file:
      - .env
    environment:
      - PUID=1001
      - PGID=1001
      - HOMEPAGE_VAR_PRX_USERNAME=$HOMEPAGE_VAR_PRX_USERNAME
      - HOMEPAGE_VAR_PRX_PASSWORD=$HOMEPAGE_VAR_PRX_PASSWORD
      - HOMEPAGE_VAR_TRUENAS_KEY=$HOMEPAGE_VAR_TRUENAS_KEY
      - HOMEPAGE_VAR_PLEX_TOKEN=$HOMEPAGE_VAR_PLEX_TOKEN
    restart: unless-stopped