---
# Docker compose file for self hosted GitLab

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: "gitlab.example.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.web.beantech.uk'
      ENTRA_CLIENT_ID:
      ENTRA_CLIENT_SECRET: 
      ENTRA_TENANT_ID: 
    ports:
      - 80:80
      - 443:443
      - 2424:22
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
    restart: unless-stopped