---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Infrastructure and Data:
    - Proxmox Node 1:
        icon: si-proxmox-#E57000
        href: https://prx-prod-01.web.beantech.uk
        description: My Proxmox cluster
        siteMonitor: https://prx-prod-01.web.beantech.uk
        widget:
            type: proxmox
            url: https://prx-prod-01.home.beantech.uk:8006
            username: {{HOMEPAGE_VAR_PRX_USERNAME}}
            password: {{HOMEPAGE_VAR_PRX_PASSWORD}}
            node: prx-prod-01

    - Proxmox Node 2:
        icon: si-proxmox-#E57000
        href: https://prx-prod-02.web.beantech.uk
        description: My Proxmox cluster
        siteMonitor: https://prx-prod-02.web.beantech.uk
        widget:
            type: proxmox
            url: https://prx-prod-02.home.beantech.uk:8006
            username: {{HOMEPAGE_VAR_PRX_USERNAME}}
            password: {{HOMEPAGE_VAR_PRX_PASSWORD}}
            node: prx-prod-02
  
    - NAS Server:
        icon: truenas.png
        href: https://nasty.web.beantech.uk
        description: My Proxmox cluster
        siteMonitor: https://nasty.web.beantech.uk
        widget:
            type: truenas
            url: https://nasty.web.beantech.uk
            key: {{HOMEPAGE_VAR_TRUENAS_KEY}}
            enablePools: true

- Media and Entertainment:
    - Plex:
        icon: si-plex-#E5A00D
        href: https://plex.web.beantech.uk
        description: My Plex server
        siteMonitor: https://plex.web.beantech.uk
    
    - qBittorrent:
        icon: si-qbittorrent-#3775A9
        href: https://qbit.web.beantech.uk
        description: My qBittorrent server
        siteMonitor: https://qbit.web.beantech.uk

    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.web.beantech.uk
        description: My Sonarr server
        siteMonitor: https://sonarr.web.beantech.uk

    - Radarr:
        icon: radarr.png
        href: https://radarr.web.beantech.uk
        description: My Radarr server
        siteMonitor: https://radarr.web.beantech.uk

    - Tautulli:
        icon: tautulli.png
        href: https://tautulli.web.beantech.uk
        description: My Tautulli server
        siteMonitor: http://srv-prod-02.home.beantech.uk:8181
        widget:
            type: tautulli
            url: https://tautulli.web.beantech.uk
            key: e6403367b2894313a4130cbaa3607ae3
            enableUser: true

- Development and DevOps:
    - GitLab:
        icon: gitlab.png
        href: https://gitlab.web.beantech.uk
        description: My GitLab server
        siteMonitor: https://gitlab.web.beantech.uk

    - Twingate:
        icon: twingate.png
        href: https://beantech.twingate.com
        description: My Twingate tenant

- Websites:
    - My Portfolio:
        href: https://www.beenhamow.co.uk
        description: My personal portfolio
        siteMonitor: https://www.beenhamow.co.uk

    - SE Team Portfolio:
        href: https://www.ljmu.dev
        description: University SE team portfolio
        siteMonitor: https://www.ljmu.dev

    - Alice's Portfolio:
        href: https://www.corkera.co.uk
        description: Alice's personal portfolio
        siteMonitor: https://www.corkers.co.uk