---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: BeanTech Homelab
background: 
  image: /images/background.png
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 25
